services:
  nginx:
    container_name: nginx_service
    restart: unless-stopped
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro 

  certbot:
    container_name: certbot_service
    restart: unless-stopped
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  aws:
    container_name: aws-cli_service
    restart: unless-stopped
    image: amazon/aws-cli
    stdin_open: true
    tty: true
    command: 's3 sync /certbot/ s3://certbot-files'
    volumes:
      - ./aws:/root/.aws/:ro # AWS Credentials (Mount '.aws/config' & '.aws/credentials' files in container /root/.aws/)
      - ./certbot/:/certbot/:ro # Files to upload to S3